[tool.poetry]
name = "llamaindex-llm"
version = "0.1.0"
description = ""
authors = ["Yi Ding <yi@fractal-llc.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
llama-index = "^0.10.53"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
